### ISSUE TITLE
novel vs. erzählung?

### ISSUE THREAD

**Issue by jberenike** [COST-ELTeC/ELTeC-deu#10]
as noted in issue#9 some of the texts are "erzählungen", but they were indeed published in book form.
e.g.DEU70 &  DEU72

**Comment by jberenike** [comment]
metadata for DEU72 indicate first print in periodical (Erstdruck in: Vom Fels zum Meer (Stuttgart), Februar- Mai 1887.) wikipedia: "Die Buchausgabe brachte Müller-Grote im selben Jahr in Berlin heraus.[1]" https://de.wikipedia.org/wiki/Im_alten_Eisen#cite_note-1

**Comment by fotisj** [comment]
Not sure I understand the issue, but if it is the question whether these texts are really novels, because they have been labeled 'Erzählungen', my answer would be: The labels 'Novelle' and 'Erzählung' cannot be taken as indicators that a text is *not* a novel, because we have very lengthy novels and the term 'Erzählung' is used for shorter tales and quite long texts. I think we can safely define a novel a text of some lenght (we can use 200 pages like E.M. Foster, or 150 pages with ca. 2500 characters as I often do) and the see whether we can find any differences which distinguish the 'Erzählungen', but I haven't seen any yet.

**Comment by jberenike** [comment]
> 
> 
> Not sure I understand the issue, but if it is the question whether these texts are really novels, because they have been labeled 'Erzählungen', my answer would be: The labels 'Novelle' and 'Erzählung' cannot be taken as indicators that a text is _not_ a novel, because we have very lengthy novels and the term 'Erzählung' is used for shorter tales and quite long texts. I think we can safely define a novel a text of some lenght (we can use 200 pages like E.M. Foster, or 150 pages with ca. 2500 characters as I often do) and the see whether we can find any differences which distinguish the 'Erzählungen', but I haven't seen any yet.

yes, thanks, that was the question. The research question "what is a novel" could indeed be approached in an empirical, text-driven, way, adopting the criterion for considering something a novel "minimal length." (if I understand you correctly) 

It would be important, though, IMHO, to keep the original genre attribution systematically in the metadata . Maybe it is already? 
BTW this is coming from the context of the "TitleStudy", in which I have been annotating the titles and sub titles of the DEU ELTeC collection https://github.com/distantreading/WG1/tree/master/titlePilotStudy

**Comment by lb42** [comment]
Closing this, since it does not seem that any correction is needed.
