### ISSUE TITLE
serial publication

### ISSUE THREAD

**Issue by jberenike** [COST-ELTeC/ELTeC-deu#7]
DEU026 and DEU034 are part 2 and 1 ("Band 2, 1") of the same publication. Do we want to include these as two separate entries?
(opend issue in WG1. Here copy-pasting @lb42 : "FWIW, I think the two volumes of this work should be treated as a single text, since that is what we do in other repositories."

**Comment by jberenike** [comment]
another serial publication: DEU003 und DEU009
Der Pedlar

DEU009: Das Vermächtnis des Pedlars Ruppius, Otto Otto Ruppius: Das Vermächtnis des Pedlars. **Folge des Romans: »Der Pedlar«,** Leipzig: Philipp Reclam jun., [o.J.]. Erstdruck: Berlin (Duncker) 1859.
German

**Comment by lb42** [comment]
You're conflating two things here: the bibliographic description of the print source which was transcribed (this is in `<bibl type='printSource'>`) and the bibliographic description of the actual first edition of the work  (this is in `<bibl type='firstEdition'>` ). And, fwiw, neither of these is the actual titlepage of the work, which if it was there would be in the transcription `<front><div type='titlepage'>...`

**Comment by lb42** [comment]
My comment doesn't really address the issue you're raising, which is whether or not the two parts of "der pedlar" should be treated as a single work. In this case I'd say not, since they were originally published as two distinct works, with two different titles. Similarly (but arguably less so) for the other case where the two "band" were originally published separately (or so I think -- I am not an expert in this domain). But it's a judgment call for the subject specialist to decide what is considered to be a complete novel. In the case of Proust, my usual example,  it seems a bit weird to consider  "A la recherche du temps perdu" as one single novel, though one might quite plausibly argue that the two parts of "Du cote de chez Swann" should be considered as one. 
Serial publication in my terminology is something quite different of course: each part of a serial is necessarily fragmentary.
